const moment = require('moment')

module.exports = [
  {
    id: 12676,
    orderId: 131542,
    stationOrderNumber: 876542,
    flightStartDate: moment().subtract(2, 'weeks').format('MM/DD/YY'),
    flightEndDate: moment().add(3, 'weeks').format('MM/DD/YY'),
    overdue: true,
    product: 'GEN',
    estimate: 23,
    primaryDemo: 'A25-54',
    totalRevenue: 12345,
    totalGrps: 123,
    totalSpots: 100,
    buyerName: 'John Doe',
    repName: 'Rep User',
    dealType: 'Cash',
    version: 1,
    scheduleType: 'Weekly',
    makegoodTotal: 1100,
    makegoodNumber: '001',
    dateMakegoodSent: moment().format('MM/DD/YY'),
    dateTimeOfferDue: moment().add(2, 'days').format('MM/DD/YY'),
    stationAction: 'N/A',
    offerType: 'Makegood',
    offerStatus: 'pending',
    agencyOrderNumber: 56789,
    acceptedByAgency: 'pending',
    agencyNotes: '',
    acceptedByStation: 'confirmed',
    stationNotes: '',
    agency: 'The Media Masters Group',
    advertiser: 'Metro Wireless',
    campaignName: 'WASHI WVVV MEW-GEN-23 Q1 17',
    cpe: 'MEW-GEN-23',
    videaOrderDetail: 'V00012543',
    videaOrderNumber: 131542,
    dateCreated: moment().format('MM/DD/YY'),
    timeCreated: '10:08:00 AM',
    dateUpdated: moment().format('MM/DD/YY'),
    timeUpdated: '10:08:00 AM',
    classification: 'Wrong or No Copy',
    preempts: [
      {
        offerId: 12676,
        orderNumber: 131542,
        stationOrderNumber: 876542,
        videaOrderNumber: 131542,
        totalAmountPreempted: 550,
        airDate: moment().subtract(1, 'weeks').weekday(2).format('MM/DD/YY'),
        stationLineNumber: 7,
        altLineNumber: 7,
        stationSpotNumber: 1,
        buyerLineNumber: 4,
        buyerDays: 'Mo-Fr',
        buyerTime: '6-7pm',
        buyerProgramOrdered: 'Network23 News @ 6',
        programPlaced: 'Network23 News This Morning',
        priority: 'P-05',
        statusName: 'Placed',
        airDay: 'Tuesday',
        length: '30 s',
        preemptReason: '[NA/Oversold]',
        currentStateDescription: '[NA/Oversold]',
        flightStartDate: moment().subtract(2, 'weeks').format('MM/DD/YY'),
        flightEndDate: moment().add(3, 'weeks').format('MM/DD/YY'),
        demo: 'P18-49',
        buyerName: 'Sarah Salinas',
        cpe: 'NEW/GEN/23',
        openMG: '[NA/Oversold]',
        agencyName: 'The Media Masters Group',
        advertiserName: 'Metro Wireless',
        campaignName: 'FY17 Metro Wireless GEN',
        productName: 'CORPORATE',
        estimate: '0016',
        revenue: '5230',
        currentGrpsImps: '',
        purchasedGrpsImps: '',
        difference: '',
        currentHouseholdGrpsImps: '',
        totalPurchasedGrpsImps: '88.3',
        demoName: ' P18-49',
        weeksRemaining: 2,
        programSpotUnitRate: 550,
        spotRate: 550,
        buyerRating: 2.0,
        buyerCpp: 275,
        airTime: '6-7pm',
        customerCareNotes: 'MARK kelley\'s note as a test. I also updated the open preempt note via the EOM screen.',
        orderStartDate: '06/27/2016',
        orderEndDate: '12/25/2016',
        weeklySpotAllocations: [
          {
            week: moment().subtract(2, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().subtract(1, 'weeks').weekday(1).format('MM/DD/YY'),
            value: 1,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(1, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(2, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(3, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(4, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(5, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(6, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(7, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(8, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(9, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(10, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          }
        ]
      },
      {
        offerId: 12674,
        orderNumber: 131542,
        stationOrderNumber: 876542,
        videaOrderNumber: 131542,
        totalAmountPreempted: 550,
        airDate: moment().subtract(1, 'weeks').weekday(4).format('MM/DD/YY'),
        stationLineNumber: 7,
        altLineNumber: 7,
        stationSpotNumber: 2,
        buyerLineNumber: 4,
        buyerDays: 'Mo-Fr',
        buyerTime: '6-7pm',
        buyerProgramOrdered: 'Network23 News @ 6',
        programPlaced: 'Network23 News This Morning',
        priority: 'P-05',
        statusName: 'Placed',
        airDay: 'Thursday',
        length: '30 s',
        preemptReason: '[NA/Oversold]',
        currentStateDescription: '[NA/Oversold]',
        flightStartDate: moment().subtract(2, 'weeks').format('MM/DD/YY'),
        flightEndDate: moment().add(3, 'weeks').format('MM/DD/YY'),
        demo: 'P18-49',
        buyerName: 'Sarah Salinas',
        cpe: 'NEW/GEN/23',
        openMG: '[NA/Oversold]',
        agencyName: 'The Media Masters Group',
        advertiserName: 'Metro Wireless',
        campaignName: 'FY17 Metro Wireless GEN',
        productName: 'CORPORATE',
        estimate: '0016',
        revenue: '5230',
        currentGrpsImps: '',
        purchasedGrpsImps: '',
        difference: '',
        currentHouseholdGrpsImps: '',
        totalPurchasedGrpsImps: '88.3',
        demoName: ' P18-49',
        weeksRemaining: 2,
        programSpotUnitRate: 550,
        spotRate: 550,
        buyerRating: 2.0,
        buyerCpp: 275,
        airTime: '6-7pm',
        customerCareNotes: 'MARK kelley\'s note as a test. I also updated the open preempt note via the EOM screen.',
        orderStartDate: '06/27/2016',
        orderEndDate: '12/25/2016',
        weeklySpotAllocations: [
          {
            week: moment().subtract(2, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().subtract(1, 'weeks').weekday(1).format('MM/DD/YY'),
            value: 1,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(1, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(2, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(3, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(4, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(5, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(6, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(7, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(8, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(9, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          },
          {
            week: moment().add(10, 'weeks').weekday(1).format('MM/DD/YY'),
            value: null,
            isHiatus: false,
            trafficSpots: null
          }
        ]
      }
    ],
    makegoods: [
      {
        lineNumber: 1,
        program: 'Network 23 News @ 5',
        startTime: '05:00 PM',
        endTime: '06:00 PM',
        days: 'M-F',
        spotLength: ':30',
        offeredSpots: 2,
        spotRate: 550,
        stationRating: 1.8,
        comment: ''
      }
    ],
    spotsOffered: [
      {
        isSelected: false,
        weeks: [
          null,
          null,
          null,
          2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        orderDays: 'M-F',
        startTime: '06:00 PM',
        endTime: '07:00 PM',
        program: 'Network23 News @ 6',
        length: '30 s',
        orderedSpots: 2,
        spotRate: 550,
        stationRating: 2.0,
        stationCpp: 275,
        makegoodComment: 'Pls confirm'
      }
    ],
    oldProgramNamesBeingReplaced: [
    ],
    newProgramming: [
    ]
  },
  {
    id: 12678,
    orderId: 131542,
    stationOrderNumber: 876542,
    flightStartDate: moment().subtract(2, 'weeks').format('MM/DD/YY'),
    flightEndDate: moment().add(3, 'weeks').format('MM/DD/YY'),
    overdue: false,
    product: 'GEN',
    estimate: 23,
    primaryDemo: 'A25-54',
    totalRevenue: 12345,
    totalGrps: 123,
    totalSpots: 100,
    buyerName: 'John Doe',
    repName: 'Rep User',
    dealType: 'Cash',
    version: 1,
    scheduleType: 'Weekly',
    makegoodTotal: null,
    makegoodNumber: '002',
    dateMakegoodSent: moment().format('MM/DD/YY'),
    dateTimeOfferDue: moment().add(2, 'days').format('MM/DD/YY'),
    stationAction: 'Accept/Reject',
    offerType: 'Program Change',
    offerStatus: 'pending',
    agencyOrderNumber: 56789,
    acceptedByAgency: 'confirmed',
    agencyNotes: '',
    acceptedByStation: 'pending',
    stationNotes: '',
    agency: 'The Media Masters Group',
    advertiser: 'Metro Wireless',
    campaignName: 'WASHI WVVV MEW-GEN-23 Q1 17',
    cpe: 'MEW-GEN-23',
    videaOrderDetail: 'V00012543',
    videaOrderNumber: 131542,
    dateCreated: moment().format('MM/DD/YY'),
    timeCreated: '11:56:00 AM',
    dateUpdated: moment().format('MM/DD/YY'),
    timeUpdated: '11:56:00 AM',
    classification: 'MG for Program Change',
    preempts: [],
    makegoods: [],
    spotsOffered: [],
    oldProgramNamesBeingReplaced: [
      {
        orderDays: 'MO-FR',
        startTime: '11:00 PM',
        endTime: '11:30 PM',
        program: 'Seinfeld',
        lineNumber: 6,
        length: '30 s',
        orderedSpots: 6,
        weeks: [
          3,
          3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        spotRate: 200,
        buyerRating: 1.1,
        buyerCpp: 182,
        lineDollarTotal: 1200
      }
    ],
    newProgramming: [
      {
        lineNumber: 6,
        orderDays: 'MO-FR',
        startTime: '11:00 PM',
        endTime: '11:30 PM',
        program: 'Modern Family',
        length: '30 s',
        orderedSpots: 6,
        weeks: [
          3,
          3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
        ],
        spotRate: 200,
        buyerRating: 1.1,
        buyerCpp: 182,
        stationRating: 1.1,
        stationCpp: 182,
        lineDollarTotal: 1200
      }
    ]
  },
  {
    id: 12389,
    orderId: 131642,
    stationOrderNumber: 875912,
    flightStartDate: moment().subtract(8, 'weeks').format('MM/DD/YY'),
    flightEndDate: moment().add(2, 'weeks').format('MM/DD/YY'),
    overdue: false,
    product: 'END',
    estimate: 57,
    primaryDemo: 'A25-54',
    totalRevenue: 12345,
    totalGrps: 123,
    totalSpots: 100,
    buyerName: 'John Doe',
    repName: 'Brian Reed',
    dealType: 'Cash',
    version: 1,
    scheduleType: 'Weekly',
    makegoodTotal: null,
    makegoodNumber: '004',
    dateMakegoodSent: '03/20/17',
    dateTimeOfferDue: '03/22/17',
    stationAction: 'N/A',
    offerType: 'Bonus',
    offerStatus: 'draft',
    agencyOrderNumber: 56789,
    acceptedByAgency: 'draft',
    agencyNotes: '',
    acceptedByStation: 'draft',
    stationNotes: '',
    agency: 'Auto Advertising Partners',
    advertiser: 'Southeast Ford',
    campaignName: 'WASHI WVVV FSE-END-22 Q1 17',
    cpe: 'FSE-END-22',
    videaOrderDetail: 'V00012321',
    videaOrderNumber: 131642,
    dateCreated: '03/20/17',
    timeCreated: '08:06:00 AM',
    dateUpdated: '03/22/17',
    timeUpdated: '04:36:00 PM',
    preempts: [],
    makegoods: [],
    spotsOffered: [],
    oldProgramNamesBeingReplaced: [],
    newProgramming: []
  },
  {
    id: 12375,
    orderId: 133529,
    stationOrderNumber: 876599,
    flightStartDate: moment().subtract(6, 'weeks').format('MM/DD/YY'),
    flightEndDate: moment().subtract(1, 'weeks').format('MM/DD/YY'),
    overdue: false,
    product: 'HOL',
    estimate: 57,
    primaryDemo: 'A25-54',
    totalRevenue: 12345,
    totalGrps: 123,
    totalSpots: 100,
    buyerName: 'John Doe',
    repName: 'Brian Reed',
    dealType: 'Cash',
    version: 1,
    scheduleType: 'Weekly',
    makegoodTotal: null,
    makegoodNumber: '007',
    dateMakegoodSent: '03/17/17',
    dateTimeOfferDue: '03/20/17',
    stationAction: 'N/A',
    offerType: 'Program Change',
    offerStatus: 'confirmed',
    agencyOrderNumber: 56789,
    acceptedByAgency: 'confirmed',
    agencyNotes: '',
    acceptedByStation: 'confirmed',
    stationNotes: '',
    agency: 'Zone Group Advertising',
    advertiser: 'Papa John’s Pizza',
    campaignName: 'WASHI WVVV PJP-HOL-8 Q1 17',
    cpe: 'PJP-HOL-8',
    videaOrderDetail: 'V00012341',
    videaOrderNumber: 133529,
    dateCreated: '03/17/17',
    timeCreated: '02:17:00 PM',
    dateUpdated: '03/20/17',
    timeUpdated: '05:37:00 PM',
    preempts: [],
    makegoods: [],
    spotsOffered: [],
    oldProgramNamesBeingReplaced: [],
    newProgramming: []
  }
]
